
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[411] =
    {   0,
        0,    0,  113,  111,  108,    1,   96,  110,  111,  102,
       95,  111,   90,   91,  100,   99,   87,   98,   94,  101,
       53,   52,   88,   84,  103,   89,  104,  107,   50,   50,
       92,   93,  105,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   85,
      106,   86,   97,   83,  110,  110,   61,    0,    4,   69,
       86,   78,   70,    0,    0,   67,   75,   65,   76,   66,
       77,    0,   56,    2,    3,   68,   57,   53,  109,  109,
      109,   53,   53,  109,   53,   52,   52,   52,   52,   93,
       85,   92,   74,   80,   82,   81,   73,   50,  110,    0,

       71,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   12,   50,   50,   50,
       50,   50,   50,   20,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   72,   79,   61,    0,
        0,    0,  110,    0,   54,    0,    0,   62,    0,   56,
        3,   56,  109,   57,    0,   55,   53,   53,   53,   53,
      109,   51,   52,   52,   52,   52,   64,   63,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   18,
       50,   50,   22,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,    0,
        0,  110,  110,    0,    0,    0,   56,  109,   56,    0,
       57,   55,   55,   53,  109,  109,   51,  109,   51,   51,
       52,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,    5,   50,    7,    8,   50,   50,   50,   50,   14,
       15,   50,   50,   19,   50,   23,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   36,   50,
       50,    0,    0,  110,  110,    0,    0,   56,   57,   55,
      109,  109,   51,   51,    0,   58,   51,   51,   50,   50,
       42,   50,   50,   50,   50,   50,   50,   50,    6,    9,

       50,   50,   50,   50,   17,   50,   50,   50,   50,   27,
       50,   50,   50,   50,   50,   50,   34,   50,   50,   38,
        0,    0,   57,    0,   59,    0,   60,   58,   58,   51,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   13,   16,   21,   50,   50,   26,   28,   29,   30,
       31,   32,   50,   50,   50,    0,    0,   59,   59,   60,
       60,   58,   50,   50,   41,   50,   50,   50,   50,   50,
       50,   50,   50,   11,   50,   50,   33,   50,   50,   59,
       60,   39,   40,   43,   44,   50,   50,   50,   50,   49,
       10,   24,   25,   35,   37,   50,   46,   50,   50,   45,

       50,   50,   50,   50,   50,   50,   50,   48,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[424] =
    {   0,
        0,    0,  834,  835,  835,  835,  808,   75,    0,   53,
       73,  787,  835,  835,  806,   69,  835,   70,   68,   80,
      105,   90,  804,  835,   92,  804,   65,  835,    0,   95,
      835,  835,  803,  125,  760,  762,   79,   40,   42,   56,
      763,   75,  762,  770,  111,  748,  125,  756,  760,  835,
       82,  835,  835,  835,  169,  174,  176,  120,    0,  835,
      835,  835,  835,   74,  132,  835,  835,  835,  835,  835,
      835,  786,  173,  835,    0,  835,  202,  210,  180,    0,
      244,  174,  103,  262,  128,    0,  200,  123,  207,  835,
      835,  835,  768,  835,  835,  835,  765,    0,  243,  744,

      835,  138,  725,  721,  729,  720,  701,  695,  696,  689,
      674,  686,  673,  688,  674,  680,  666,  667,  664,  664,
      667,  664,  661,    0,  149,  665,  185,  663,   97,   82,
      667,  660,  717,  152,  126,  664,  835,  835,  266,  139,
      715,  183,  282,    0,  835,  280,    0,  835,  311,  835,
        0,  285,  322,    0,  286,  327,  212,    0,  680,  657,
      369,  312,  218,    0,  677,  652,  835,  835,  653,  647,
      646,  646,  644,  655,  635,  649,  633,  628,  632,  644,
      638,  625,  159,  639,  637,  632,  624,  630,  633,    0,
      619,  619,    0,  620,  606,  596,  593,  594,  596,  603,

      589,  587,  587,  599,  589,  593,  591,  592,  581,  231,
      291,  348,  422,  350,  468,  337,  411,  390,    0,  364,
      394,  472,    0,    0,  207,  233,  391,  514,  216,  397,
        0,  584,  573,  573,  568,  577,  574,  575,  553,  565,
      556,    0,  558,    0,    0,  548,  556,  545,  552,    0,
        0,  546,  543,    0,  547,    0,  542,  542,  540,  537,
      549,  538,  542,  546,  545,  543,  532,  537,    0,  525,
      537,  461,    0,  318,    0,  325,    0,  518,  524,  835,
      545,  555,  310,    0,  416,  561,  548,  525,  510,  512,
        0,  508,  498,  502,  490,  497,  504,  501,    0,    0,

      489,  482,  487,  469,    0,  475,  459,  467,  462,    0,
      464,  461,  463,  446,  455,  457,    0,  446,  447,    0,
      463,  616,  835,  441,  568,  528,  605,  653,    0,    0,
      224,  452,  449,  438,  433,  418,  433,  431,  430,  402,
      397,    0,    0,    0,  404,  398,    0,    0,    0,    0,
        0,    0,  392,  392,  379,  331,    0,  659,    0,  682,
        0,  835,  360,  363,    0,  346,  356,  357,  340,  348,
      346,  344,  338,    0,  316,  312,    0,  322,  320,  835,
      835,    0,    0,    0,    0,  308,  304,  313,  262,    0,
        0,    0,    0,    0,    0,  248,    0,  237,  235,    0,

      193,  193,  185,  158,  125,   74,   47,    0,    0,  835,
      741,  750,  759,  764,  768,  775,  782,  791,  800,  804,
      806,  811,  815
    } ;

static const flex_int16_t yy_def[424] =
    {   0,
      410,    1,  410,  410,  410,  410,  410,  411,  412,  410,
      410,  413,  410,  410,  410,  410,  410,  410,  410,  410,
      414,  414,  410,  410,  410,  410,  410,  410,  415,  415,
      410,  410,  410,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  410,
      410,  410,  410,  410,  411,  411,  410,  416,  412,  410,
      410,  410,  410,  413,  417,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  418,  410,  414,   22,  414,  414,
      414,  414,  414,  414,  414,   22,  414,  414,  414,  410,
      410,  410,  410,  410,  410,  410,  410,  415,  411,  413,

      410,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  410,  410,  410,  419,
      410,  410,  411,  420,  410,  413,  421,  410,  410,  410,
      418,   77,  414,  414,  410,  414,  414,  414,  414,  414,
      414,   84,  414,  414,  414,  414,  410,  410,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  419,
      422,  411,  411,  413,  413,  410,  410,  414,  414,  410,
       77,  410,  414,  414,  161,  161,  414,  414,  414,  414,
      414,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  419,  423,  411,  213,  413,  215,  414,  410,  410,
      414,  414,  414,  414,  410,  414,  414,  414,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      419,  419,  410,  410,  414,  410,  414,  410,  414,  414,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  419,  322,  410,  414,  410,
      414,  410,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  410,
      410,  415,  415,  415,  415,  415,  415,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  415,

      415,  415,  415,  415,  415,  415,  415,  415,  415,    0,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410
    } ;

static const flex_int16_t yy_nxt[912] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   30,   29,   31,    4,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   29,   42,   29,   43,   29,
       29,   29,   29,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   56,   60,   61,   57,
       62,   67,  145,   72,   69,   73,   73,   73,   73,   96,
       97,   74,  116,   68,   70,   71,   75,   63,   91,   99,

      118,  117,  119,  100,   76,   77,  137,   86,   86,   86,
       86,  120,  409,   92,  121,   93,   94,  122,   65,   58,
       77,   81,   78,   78,   79,   79,   87,  113,  124,   99,
      201,   88,  408,  100,  114,  125,   81,  143,  143,  159,
      115,   82,   81,   57,  133,  202,   83,   84,   89,  146,
      146,  199,  102,  103,  104,  138,   88,   81,  105,  165,
      106,  160,  107,   85,  108,  109,  128,  129,  200,  158,
       56,   83,  110,   57,   84,   56,  130,  139,   57,  131,
      140,  166,  207,  211,  208,  134,  157,  140,  407,  144,
       73,   73,   73,   73,  158,   77,  169,   79,   79,   79,

       79,  147,  141,  170,  149,  150,  406,  192,  205,  150,
      157,   81,  141,   58,  193,  158,  206,  141,   58,  152,
      152,  152,  152,  246,  247,  149,  150,   78,   78,   79,
       79,  150,   81,  153,  154,   57,  163,  405,  154,  195,
      158,  164,  142,  404,   56,  281,   82,   57,  164,  196,
      197,   83,  287,  158,  153,  154,  155,  403,  155,  164,
      154,  156,  156,  156,  156,  163,  164,  139,   85,  281,
      140,  282,  363,  164,  288,  211,   83,  161,  158,  162,
      162,  162,  162,   56,  164,  364,   57,   58,  145,  162,
      162,  162,  162,  162,  162,  282,  402,  214,  214,  212,

      212,  401,  141,  222,  222,  222,  222,  141,  272,  272,
      162,  162,  162,  162,  162,  162,  218,  219,  400,   56,
      399,  219,   57,  216,   65,  216,   58,  226,  217,  217,
      217,  217,  142,  145,  220,   57,  220,  218,  219,  221,
      221,  221,  221,  219,  156,  156,  156,  156,  227,   56,
      228,  284,   57,  229,  217,  217,  217,  217,  145,  223,
      273,  398,   58,  223,  397,  274,  274,  276,  276,   65,
      230,  396,  395,  394,  228,  211,  284,  393,  229,  392,
      223,  279,  279,  279,  279,  223,  225,  225,  225,  225,
      391,  390,   58,  389,   65,  388,  225,  225,  225,  225,

      225,  225,  216,  387,  216,  386,  385,  278,  278,  278,
      278,  221,  221,  221,  221,  384,  383,  225,  225,  225,
      225,  225,  225,   56,  382,   80,   57,  283,  217,  217,
      217,  217,  284,  328,  328,  328,  328,  379,  284,  275,
      275,  275,  275,  150,  378,  377,   80,  150,  376,  275,
      275,  275,  275,  275,  275,  283,  375,  284,  358,  358,
      358,  358,  374,  284,  150,   57,   58,   57,  373,  150,
      275,  275,  275,  275,  275,  275,  145,  372,  321,  321,
      356,  356,  371,  370,  369,  277,  277,  277,  277,  222,
      222,  222,  222,  368,  367,  277,  277,  277,  277,  277,

      277,  366,  365,  355,  280,  211,  354,  211,  280,  353,
      352,  351,   65,  350,  349,  348,  277,  277,  277,  277,
      277,  277,  347,  346,  345,  280,  285,  344,  285,  343,
      280,  286,  286,  286,  286,  278,  278,  278,  278,  342,
      341,  279,  279,  279,  279,  360,  360,  360,  360,  340,
      219,  339,  338,  337,  219,  336,  323,  324,  335,  324,
      323,  334,  325,  325,  325,  325,  333,  326,  332,  326,
      331,  219,  327,  327,  327,  327,  219,  323,  286,  286,
      286,  286,  323,  330,  330,  325,  325,  325,  325,  320,
      319,  318,  317,  329,  316,  315,  314,  329,  313,  312,

      359,  311,  310,  309,  359,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  329,  299,  298,  297,  296,  329,
       57,  359,  327,  327,  327,  327,  359,  295,  294,  293,
      292,  291,  290,  357,  357,  357,  357,  361,  289,  271,
      270,  361,  269,  357,  357,  357,  357,  357,  357,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  361,  259,
      211,  258,  257,  361,  357,  357,  357,  357,  357,  357,
      328,  328,  328,  328,  256,  255,  358,  358,  358,  358,
      254,  253,  252,  251,  250,  362,  249,  248,  245,  362,
      244,  380,  243,  242,  241,  380,  240,  239,  238,  360,

      360,  360,  360,  237,  236,  235,  362,  234,  233,  232,
      231,  362,  380,  231,  381,  224,  224,  380,  381,  140,
      209,   99,  204,  203,  198,  194,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  381,  182,  181,  180,  179,
      381,   55,  178,   55,   55,   55,   55,   55,   55,   55,
       59,  177,   59,   59,   59,   59,   59,   59,   59,   64,
      176,   64,  175,   64,   64,   64,   64,   64,   80,   80,
       80,   80,   80,   98,   98,   98,   98,   55,   55,  174,
       55,  173,  172,   55,   64,   64,  171,   64,   65,  168,
       64,  151,  167,  151,  151,  151,  151,  151,  151,  151,

      210,  148,  210,  210,  210,  210,  210,  210,  210,  213,
      213,  215,  215,  210,  210,  136,  210,  135,  132,  210,
      322,  322,  127,  126,  123,  112,  111,  101,   95,   90,
       66,   65,   54,  410,    3,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410
    } ;

static const flex_int16_t yy_chk[912] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   10,   10,    8,
       11,   16,   64,   19,   18,   19,   19,   19,   19,   27,
       27,   20,   38,   16,   18,   18,   20,   11,   25,   30,

       39,   38,   39,   30,   20,   22,   51,   22,   22,   22,
       22,   39,  407,   25,   40,   25,   25,   40,   64,    8,
       21,   22,   21,   21,   21,   21,   22,   37,   42,   47,
      130,   22,  406,   47,   37,   42,   21,   58,   58,   83,
       37,   21,   22,  140,   47,  130,   21,   21,   22,   65,
       65,  129,   34,   34,   34,   51,   22,   21,   34,   88,
       34,   83,   34,   21,   34,   34,   45,   45,  129,   85,
       55,   21,   34,   55,   21,   56,   45,   57,   56,   45,
       57,   88,  135,  140,  135,   47,   85,  142,  405,   58,
       73,   73,   73,   73,   85,   79,  102,   79,   79,   79,

       79,   65,  142,  102,   73,   73,  404,  125,  134,   73,
       82,   79,   57,   55,  125,   82,  134,   57,   56,   77,
       77,   77,   77,  183,  183,   73,   73,   78,   78,   78,
       78,   73,   79,   77,   77,  210,   87,  403,   77,  127,
       82,   87,   57,  402,   99,  225,   78,   99,   89,  127,
      127,   78,  229,  157,   77,   77,   81,  401,   81,  163,
       77,   81,   81,   81,   81,   89,   87,  139,   78,  225,
      139,  226,  331,   89,  229,  210,   78,   84,  157,   84,
       84,   84,   84,  143,  163,  331,  143,   99,  146,   84,
       84,   84,   84,   84,   84,  226,  399,  146,  146,  143,

      143,  398,  139,  155,  155,  155,  155,  139,  211,  211,
       84,   84,   84,   84,   84,   84,  152,  152,  396,  274,
      389,  152,  274,  149,  146,  149,  143,  162,  149,  149,
      149,  149,  139,  276,  153,  356,  153,  152,  152,  153,
      153,  153,  153,  152,  156,  156,  156,  156,  162,  212,
      162,  283,  212,  162,  216,  216,  216,  216,  214,  156,
      211,  388,  274,  156,  387,  212,  212,  214,  214,  276,
      162,  386,  379,  378,  162,  356,  283,  376,  162,  375,
      156,  220,  220,  220,  220,  156,  161,  161,  161,  161,
      373,  372,  212,  371,  214,  370,  161,  161,  161,  161,

      161,  161,  218,  369,  218,  368,  367,  218,  218,  218,
      218,  221,  221,  221,  221,  366,  364,  161,  161,  161,
      161,  161,  161,  213,  363,  221,  213,  227,  217,  217,
      217,  217,  227,  285,  285,  285,  285,  355,  230,  213,
      213,  213,  213,  217,  354,  353,  221,  217,  346,  213,
      213,  213,  213,  213,  213,  230,  345,  227,  324,  324,
      324,  324,  341,  230,  217,  272,  213,  321,  340,  217,
      213,  213,  213,  213,  213,  213,  215,  339,  272,  272,
      321,  321,  338,  337,  336,  215,  215,  215,  215,  222,
      222,  222,  222,  335,  334,  215,  215,  215,  215,  215,

      215,  333,  332,  319,  222,  272,  318,  321,  222,  316,
      315,  314,  215,  313,  312,  311,  215,  215,  215,  215,
      215,  215,  309,  308,  307,  222,  228,  306,  228,  304,
      222,  228,  228,  228,  228,  278,  278,  278,  278,  303,
      302,  279,  279,  279,  279,  326,  326,  326,  326,  301,
      278,  298,  297,  296,  278,  295,  279,  281,  294,  281,
      279,  293,  281,  281,  281,  281,  292,  282,  290,  282,
      289,  278,  282,  282,  282,  282,  278,  279,  286,  286,
      286,  286,  279,  288,  287,  325,  325,  325,  325,  271,
      270,  268,  267,  286,  266,  265,  264,  286,  263,  262,

      325,  261,  260,  259,  325,  258,  257,  255,  253,  252,
      249,  248,  247,  246,  286,  243,  241,  240,  239,  286,
      322,  325,  327,  327,  327,  327,  325,  238,  237,  236,
      235,  234,  233,  322,  322,  322,  322,  327,  232,  209,
      208,  327,  207,  322,  322,  322,  322,  322,  322,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  327,  197,
      322,  196,  195,  327,  322,  322,  322,  322,  322,  322,
      328,  328,  328,  328,  194,  192,  358,  358,  358,  358,
      191,  189,  188,  187,  186,  328,  185,  184,  182,  328,
      181,  358,  180,  179,  178,  358,  177,  176,  175,  360,

      360,  360,  360,  174,  173,  172,  328,  171,  170,  169,
      166,  328,  358,  165,  360,  160,  159,  358,  360,  141,
      136,  133,  132,  131,  128,  126,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  360,  114,  113,  112,  111,
      360,  411,  110,  411,  411,  411,  411,  411,  411,  411,
      412,  109,  412,  412,  412,  412,  412,  412,  412,  413,
      108,  413,  107,  413,  413,  413,  413,  413,  414,  414,
      414,  414,  414,  415,  415,  415,  415,  416,  416,  106,
      416,  105,  104,  416,  417,  417,  103,  417,  100,   97,
      417,  418,   93,  418,  418,  418,  418,  418,  418,  418,

      419,   72,  419,  419,  419,  419,  419,  419,  419,  420,
      420,  421,  421,  422,  422,   49,  422,   48,   46,  422,
      423,  423,   44,   43,   41,   36,   35,   33,   26,   23,
       15,   12,    7,    3,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c11.lex"
/*
 * c11.lex: An C11 scanner
 * 
 */
/* Some useful grammar */
#line 26 "c11.lex"
#include <stdio.h>

/* C token types */
#define KEYWORD_TOK 1
#define IDENTIFIER_TOK 2
#define I_CONSTANT_TOK 3
#define F_CONSTANT_TOK 4
#define C_CONSTANT_TOK 5
#define STRING_LITERAL_TOK 6
#define PUNCTUATOR_TOK 7

/* statistics */
int charCount = 0;
int lineCount = 1;
int columnCount = 1;
int keywordCount = 0;
int identifierCount = 0;
int integerConst = 0;
int floatingConst = 0;
int charConst = 0;
int stringCount = 0;
int punctuatorCount = 0;
int errorCount = 0;

/* handle errors */
void yyerror(const char *);

/* handle multi-line comments */
static void comment(void);
#line 821 "lex.yy.c"
#line 822 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 57 "c11.lex"

#line 1041 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 411 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 835 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 58 "c11.lex"
{ lineCount++; columnCount=0; return -1; } /* wrap */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "c11.lex"
{ comment(); return -1; }   /* multi-line comment begins */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "c11.lex"
{ return -1; }  /* single-line comment */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "c11.lex"
{ return -1; }  /* macro */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "c11.lex"
{ return KEYWORD_TOK; } /* keywords */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 79 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 80 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 85 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 86 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 87 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 88 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 89 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 98 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "c11.lex"
{ return KEYWORD_TOK; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "c11.lex"
{}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "c11.lex"
{ return IDENTIFIER_TOK; }  /* identifiers */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 111 "c11.lex"
{ return I_CONSTANT_TOK; }  /* constants */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "c11.lex"
{ return I_CONSTANT_TOK; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 113 "c11.lex"
{ return I_CONSTANT_TOK; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "c11.lex"
{ return C_CONSTANT_TOK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 117 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 118 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 119 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 120 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 121 "c11.lex"
{ return F_CONSTANT_TOK; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "c11.lex"
{ return STRING_LITERAL_TOK; }  /* strings literal */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "c11.lex"
{ return PUNCTUATOR_TOK; }  /* punctuators */
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 126 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 127 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 128 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 129 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 130 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 131 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 132 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 133 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 134 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 135 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 136 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 137 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 138 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 139 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 140 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 141 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 142 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 143 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 144 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 145 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 146 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 147 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 148 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 149 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 150 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 151 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 152 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 153 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 154 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 156 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 157 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 158 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 159 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 160 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 161 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 162 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 163 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 164 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 165 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 166 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 167 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 168 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 169 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 170 "c11.lex"
{ return PUNCTUATOR_TOK; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 172 "c11.lex"
{return -1;}    /* white space */
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 174 "c11.lex"
{ yyerror("illegal name"); return -1; } /* errors */
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 175 "c11.lex"
{ yyerror("unclosed string"); return -1; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 176 "c11.lex"
{ yyerror("unexpected character"); return -1; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 178 "c11.lex"
ECHO;
	YY_BREAK
#line 1659 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 411 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 411 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 410);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "c11.lex"


void yyerror(const char *err)
{
    errorCount++;
    fprintf(stderr, "\033[1m%d:%d: \033[31mError: \033[32m%s\033[39m %s\n\033[0m", lineCount, columnCount, err, yytext);
}

static void comment(void)
{
    int c;

    while ((c = input()) != 0)
    {
        charCount++;
        if (c == '\n')
            lineCount++;
        if (c == '*')
        {
            while ((c = input()) == '*')
            {
                charCount++;
            }
            charCount++;
            if (c == '\n')
            {
                lineCount++;
                columnCount = 1;
            }

            if (c == '/')
            {
                return;
            }

            if (c == 0)
                break;
        }
    }
    yyerror("unterminated comment");
}

int main()
{
    int code;
    while ((code = yylex()))    // code is the type of token
    {
        charCount += yyleng;    // character counts
        switch (code)
        {
        case KEYWORD_TOK:
            keywordCount++;
            printf("%d:%d: [Keyword: %s]\n", lineCount, columnCount, yytext);
            break;
        case IDENTIFIER_TOK:
            identifierCount++;
            printf("%d:%d: [Identifier: %s]\n", lineCount, columnCount, yytext);
            break;
        case I_CONSTANT_TOK:
            integerConst++;
            printf("%d:%d: [Integer: %s]\n", lineCount, columnCount, yytext);
            break;
        case C_CONSTANT_TOK:
            charConst++;
            printf("%d:%d: [Character: %s]\n", lineCount, columnCount, yytext);
            break;
        case F_CONSTANT_TOK:
            floatingConst++;
            printf("%d:%d: [Floating: %s]\n", lineCount, columnCount, yytext);
            break;
        case STRING_LITERAL_TOK:
            stringCount++;
            printf("%d:%d: [String: %s]\n", lineCount, columnCount, yytext);
            break;
        case PUNCTUATOR_TOK:
            punctuatorCount++;
            printf("%d:%d: [Punctuator: %s]\n", lineCount, columnCount, yytext);
            break;
        default:
            break;
        }
        columnCount += yyleng;  // cursor forward
    }
    printf("\nTotal characters:\t%d\n", charCount);
    printf("Total lines:\t%d\n", lineCount);
    printf("\n");
    printf("Keyword:\t%d\n", keywordCount);
    printf("Identifier:\t%d\n", identifierCount);
    printf("Integers:\t%d\n", integerConst);
    printf("Floatings:\t%d\n", floatingConst);
    printf("Characters:\t%d\n", charConst);
    printf("Strings:\t%d\n", stringCount);
    printf("Punctuators:\t%d\n", punctuatorCount);
    printf("\033[1mErrors:\t\t%d\n\033[0m", errorCount);
    return 0;
}
